config/routes.rb
Rails.application.routes.draw do
  resources :memes
  get '/home/index'
  get '/home/memes'
  get '/home/services'
  get '/home/contact'
  get '/memes/new'
  get '/home/memes'

  root to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
#   validates :name, uniqueness: true
#   validates :bikeType, presence: true
# end

app/models/meme.rb
class Meme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :is_paid?, only: [:show]
  def is_paid?
    # check if user has paid for da memes
    # if not paid then restrict access

  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def toogle_published
    @banner.toggle! :published
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: [:show, :edit, :update, :destroy]

  # GET /memes
  # GET /memes.json
  def index
    @memes = Meme.all
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
  end

  # GET /memes/new
  def new
    @meme = Meme.new
  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)

    respond_to do |format|
      if @meme.save
        format.html { redirect_to @meme, notice: 'Meme was successfully created.' }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { render :new }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memes/1
  # PATCH/PUT /memes/1.json
  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { render :edit }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme.destroy
    respond_to do |format|
      format.html { redirect_to memes_url, notice: 'Meme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meme_params
      params.require(:meme).permit(:meme_url)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def services
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/home/contact.html.erb
<h1>Reach out to us</h1>
<p>In this page you can find all the information to contact us.</p>

app/views/home/index.html.erb
<div class="index-page">
  
</div>

app/views/home/memes.html.erb
<div class="index-page">
  <h1 class="home-header">You can see memes here :))))))))))))))))</h1>
  <div class="images-row">
    <img src="https://data.whicdn.com/images/342876776/original.jpg" alt="img" width="400" height="400">
  
    
  </div>

</div>

app/views/home/services.html.erb
<h1>Our services</h1>
<p>Have a look at some of our services we provide to our clients</p>

<table>
  <thead>
  <tr>
    <th colspan="2">Services</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>We provide memes</td>
    <td>Only $99.99</td>
  </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TASK5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        MemeHub
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>

    <div class="nav-links">
        <%= link_to "Home", root_path %>
        <%= link_to "Memes", home_memes_path %>
        <%= link_to "Services", home_services_path %>
        <%= link_to "Admin", memes_path %>
    </div>
  </div>
      <%= yield %>
  </body>
  <!-- Site footer -->
  <!-- <footer class="site-footer">

  #   <div class="container">
  #     <div class="row">
  #         <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by PI18E
  #         </p>
  #     </div>
  #   </div>
  # </footer>
  -->
</html>

app/views/memes/_form.html.erb
<%= form_with(model: meme, local: true) do |form| %>
  <% if meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
        <% meme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meme_url %>
    <%= form.text_field :meme_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memes/edit.html.erb
<h1>Editing Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Show', @meme %> |
<%= link_to 'Back', memes_path %>

app/views/memes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memes</h1>

<table>
  <thead>
    <tr>
      <th>Meme url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memes.each do |meme| %>
      <tr>
      
        <td> <img src="<%= meme.meme_url %>" alt="img" height="200" /> </td>
        <td><%= link_to 'Show', meme %></td>
        <td><%= link_to 'Edit', edit_meme_path(meme) %></td>
        <td><%= link_to 'Destroy', meme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meme', new_meme_path %>

app/views/memes/new.html.erb
<h1>New Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Back', memes_path %>

app/views/memes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meme url:</strong>
  <%= @meme.meme_url %>
</p>

<%= link_to 'Edit', edit_meme_path(@meme) %> |
<%= link_to 'Back', memes_path %>